### ISSUE TITLE
Mac端直接点击生成语音报错

### ISSUE THREAD

**Issue by honghaifeng** [FunAudioLLM/CosyVoice#401]
2024-09-15 09:19:12,581 DEBUG Prefix dict has been built successfully.
['我是通义实验室语音团队全新推出的生成式语音大模型，', '提供舒适自然的语音合成能力。、。']
我是通义实验室语音团队全新推出的生成式语音大模型，
/Users/honghaifeng/Desktop/haifeng/2024/202409/CosyVoice_for_MacOs/cosyvoice/llm/llm.py:110: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/torch/amp/autocast_mode.py:265: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
tensor([[-0.0263, -0.0244, -0.0050,  ...,  0.0890,  0.0922,  0.0988]])
[-0.02634298 -0.02440543 -0.00499381 ...  0.08895338  0.09224407
  0.09876685]
提供舒适自然的语音合成能力。、。
tensor([[-2.9298e-02, -2.2807e-02, -1.3950e-02,  ...,  4.3468e-07,
          4.5650e-06,  3.5238e-06]])
[-2.9298300e-02 -2.2807050e-02 -1.3949540e-02 ...  4.3467713e-07
  4.5650258e-06  3.5238152e-06]
[tensor([[-0.0263, -0.0244, -0.0050,  ...,  0.0890,  0.0922,  0.0988]]), tensor([[-2.9298e-02, -2.2807e-02, -1.3950e-02,  ...,  4.3468e-07,
          4.5650e-06,  3.5238e-06]])]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/gradio/queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/gradio/blocks.py", line 1945, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/gradio/blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/gradio/utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/honghaifeng/Desktop/haifeng/2024/202409/CosyVoice_for_MacOs/webui.py", line 234, in generate_audio
    output = cosyvoice.inference_sft(tts_text,sft_dropdown,new_dropdown,spk_mix,w1,w2,token_max_n,token_min_n,merge_len)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/honghaifeng/Desktop/haifeng/2024/202409/CosyVoice_for_MacOs/cosyvoice/cli/cosyvoice.py", line 19, in wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/honghaifeng/Desktop/haifeng/2024/202409/CosyVoice_for_MacOs/cosyvoice/cli/cosyvoice.py", line 231, in inference_sft
    torchaudio.save(f"{ROOT_DIR}/output/output.wav", audio_data, 22050)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/torchaudio/_backend/utils.py", line 312, in save
    backend = dispatcher(uri, format, backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.11/site-packages/torchaudio/_backend/utils.py", line 222, in dispatcher
    raise RuntimeError(f"Couldn't find appropriate backend to handle uri {uri} and format {format}.")
RuntimeError: Couldn't find appropriate backend to handle uri /Users/honghaifeng/Desktop/haifeng/2024/202409/CosyVoice_for_MacOs/output/output.wav and format None.

**Comment by aluminumbox** [comment]
never see this error, maybe consult other users in dingding group

**Comment by alkaidzone** [comment]
same problem

**Comment by colossatr0n** [comment]
Installing soundfile as described [here](https://stackoverflow.com/a/79493731) worked for me:
```
pip install torchaudio soundfile
```

**Comment by lonelygo** [comment]
我fork 的版本提供了 macOS 下的支持，你可以试试看：https://github.com/lonelygo/CosyVoice
